# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 11:53
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consortium', models.CharField(choices=[('GOIP', 'GOIP'), ('E-WASTE', 'E-WASTE'), ('TRAINING', 'TRAINING'), ('G4S', 'G4S')], default='GOIP', max_length=300)),
                ('serial_no', models.CharField(max_length=300)),
                ('esc_issue', models.CharField(max_length=300)),
                ('resolved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('enrollment', models.IntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('electricity_availability', models.BooleanField(default=False)),
                ('total_devices_present', models.IntegerField(default=0)),
                ('emmis_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.School'),
        ),
    ]
