# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='when',
            field=models.DateField(auto_now=True, verbose_name='DATE'),
        ),
    ]
