# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170915_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
