# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170915_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date',
            field=models.DateField(),
        ),
    ]
