# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 12:10
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170915_1457'),
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict, null=True)),
                ('geo', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
